#!/usr/bin/env python3
"""
build_community_sequence_tables.py

Reconstructs the sequence composition of PGGB communities generated by
partition-before-pggb.

The script reads the community FASTA files directly from:

    PGGB_results_24G/24G_partition_results/*.fa

These FASTA files are the authoritative partition output and contain the
PanSN headers used for the subsequent PGGB runs.

Expected PanSN header:

    sample#haplotype#contig

Examples:

    Mror_B3#1#Mror_B3_Group1
    Mror_CO84#1#Mror_CO84_Ungrouped1
    Mror_Co67#1#0001

The five chromosome-scale PacBio genomes are detected after normalization:

    B3, C26, CO8, CO84, E7

Outputs
-------
1. community_sequence_inventory.tsv
   One row per sequence, with sample, contig, length, technology,
   grouped/ungrouped classification, and syntenic-group annotation.

2. community_summary.tsv
   One row per community, including:
     - total number of sequences
     - total number of genomes represented
     - one count column per genome
     - presence of all five PacBio genomes
     - PacBio grouped and ungrouped sequence counts and lists
     - detected PacBio syntenic groups

3. pacbio_chromosome_to_communities.tsv
   One row per canonical PacBio chromosome/ungrouped sequence label,
   showing the samples and communities in which that label occurs.

Additional output
-----------------
4. candidate_communities_all_5_pacbio.tsv
   Subset of community_summary.tsv containing communities in which all
   five PacBio genomes are represented.

Usage
-----
    python build_community_sequence_tables.py

Configuration is read from environment variables:

    PARTITION_DIR
    OUTPUT_DIR
    PACBIO_SAMPLES

PACBIO_SAMPLES is comma-separated and defaults to:

    B3,C26,CO8,CO84,E7
"""

from __future__ import annotations

import csv
import gzip
import os
import re
import sys
from collections import Counter, defaultdict
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Iterable, TextIO


# =========================
# CONFIGURATION
# =========================

PARTITION_DIR = Path(
    os.environ.get(
        "PARTITION_DIR",
        "/Storage/data1/isabella.gallego/MAESTRIA/"
        "PGGB_results_24G/24G_partition_results",
    )
)

OUTPUT_DIR = Path(
    os.environ.get(
        "OUTPUT_DIR",
        "/Storage/data1/isabella.gallego/MAESTRIA/"
        "PGGB_results_24G/community_sequence_tables",
    )
)

PACBIO_SAMPLES = [
    value.strip()
    for value in os.environ.get(
        "PACBIO_SAMPLES",
        "B3,C26,CO8,CO84,E7",
    ).split(",")
    if value.strip()
]

COMMUNITY_GLOB = os.environ.get(
    "COMMUNITY_GLOB",
    "*.community.*.fa",
)


# =========================
# DATA MODEL
# =========================

@dataclass
class SequenceRecord:
    """Information extracted for one community FASTA sequence."""

    community: str
    sequence_header: str
    sample_raw: str
    sample: str
    haplotype: str
    contig_raw: str
    contig: str
    length_bp: int
    technology: str
    is_pacbio: bool
    sequence_class: str
    syntenic_group: str


# =========================
# GENERAL HELPERS
# =========================

def natural_key(value: str) -> list[object]:
    """Natural-sort strings containing numbers."""
    return [
        int(token) if token.isdigit() else token.lower()
        for token in re.split(r"(\d+)", value)
    ]


def open_text(path: Path) -> TextIO:
    """Open plain-text or gzip-compressed files."""
    if path.suffix == ".gz":
        return gzip.open(path, "rt", encoding="utf-8", errors="replace")

    return path.open(
        "r",
        encoding="utf-8",
        errors="replace",
    )


def normalize_sample(sample_raw: str) -> str:
    """
    Normalize sample names to compact biological identifiers.

    Examples:
        Mror_B3   -> B3
        Mror_C26  -> C26
        Mror_CO84 -> CO84
        Mror_Co67 -> Co67

    Only the leading 'Mror_' prefix is removed. Internal underscores are
    retained for Illumina names such as Mror_1466_REFE.
    """
    return re.sub(
        r"^Mror_",
        "",
        sample_raw,
        flags=re.IGNORECASE,
    )


def normalize_contig(contig_raw: str, sample_raw: str, sample: str) -> str:
    """
    Remove duplicated sample prefixes from a contig name when present.

    Examples:
        Mror_B3_Group1  -> Group1
        B3_Group1       -> Group1
        Mror_CO84_Ungrouped1 -> Ungrouped1
        0001            -> 0001
    """
    cleaned = contig_raw.strip()

    prefixes = [
        f"{sample_raw}_",
        f"{sample}_",
        f"Mror_{sample}_",
    ]

    for prefix in prefixes:
        if cleaned.lower().startswith(
            prefix.lower()
        ):
            return cleaned[len(prefix):]

    return cleaned


def classify_contig(contig: str) -> tuple[str, str]:
    """
    Classify a normalized contig as grouped, ungrouped, or other.

    Returns
    -------
    tuple
        (sequence_class, syntenic_group)

    Examples:
        Group1       -> ("grouped", "Group1")
        group10      -> ("grouped", "Group10")
        Ungrouped3   -> ("ungrouped", "Ungrouped3")
        ungrouped_5  -> ("ungrouped", "Ungrouped5")
        0001         -> ("other", "")
    """
    compact = re.sub(
        r"[\s_-]+",
        "",
        contig,
    )

    grouped_match = re.search(
        r"(?:^|[^A-Za-z])Group(\d+)(?:$|[^0-9])",
        contig,
        flags=re.IGNORECASE,
    )

    if not grouped_match:
        grouped_match = re.fullmatch(
            r"Group(\d+)",
            compact,
            flags=re.IGNORECASE,
        )

    if grouped_match:
        group_number = int(
            grouped_match.group(1)
        )

        return (
            "grouped",
            f"Group{group_number}",
        )

    ungrouped_match = re.search(
        r"Ungrouped(?:[_-]?)(\d+)?",
        contig,
        flags=re.IGNORECASE,
    )

    if ungrouped_match:
        suffix = ungrouped_match.group(1)

        label = (
            f"Ungrouped{int(suffix)}"
            if suffix
            else "Ungrouped"
        )

        return (
            "ungrouped",
            label,
        )

    return (
        "other",
        "",
    )


def parse_pansn_header(header: str) -> tuple[str, str, str]:
    """
    Parse a PanSN header as sample#haplotype#contig.

    The split is limited to two separators so that additional '#' characters
    in a contig name are retained.
    """
    parts = header.split(
        "#",
        2,
    )

    if len(parts) != 3:
        raise ValueError(
            f"Header is not valid PanSN sample#haplotype#contig: {header}"
        )

    return (
        parts[0],
        parts[1],
        parts[2],
    )


def read_fasta_lengths(path: Path) -> Iterable[tuple[str, int]]:
    """
    Yield (header, sequence_length) from a FASTA file without loading the
    complete file into memory.
    """
    current_header: str | None = None
    current_length = 0

    with open_text(path) as handle:
        for raw_line in handle:
            line = raw_line.strip()

            if not line:
                continue

            if line.startswith(">"):
                if current_header is not None:
                    yield (
                        current_header,
                        current_length,
                    )

                current_header = line[1:].split(
                    None,
                    1,
                )[0]

                current_length = 0

            else:
                if current_header is None:
                    raise ValueError(
                        f"Sequence data found before the first FASTA header "
                        f"in {path}"
                    )

                current_length += len(
                    line
                )

    if current_header is not None:
        yield (
            current_header,
            current_length,
        )


def extract_community_name(path: Path) -> str:
    """Extract community.N from a partition FASTA filename."""
    match = re.search(
        r"(community\.\d+)",
        path.name,
    )

    if not match:
        raise ValueError(
            f"Could not extract community identifier from: {path.name}"
        )

    return match.group(1)


# =========================
# INVENTORY CONSTRUCTION
# =========================

def build_inventory(
    fasta_paths: list[Path],
) -> list[SequenceRecord]:
    """Build the complete one-row-per-sequence inventory."""
    records: list[SequenceRecord] = []

    for index, fasta_path in enumerate(
        fasta_paths,
        start=1,
    ):
        community = extract_community_name(
            fasta_path
        )

        print(
            f"  [{index}/{len(fasta_paths)}] "
            f"{community}: {fasta_path.name}",
            flush=True,
        )

        for header, length_bp in read_fasta_lengths(
            fasta_path
        ):
            try:
                (
                    sample_raw,
                    haplotype,
                    contig_raw,
                ) = parse_pansn_header(
                    header
                )
            except ValueError as error:
                print(
                    f"[ERROR] {error}",
                    flush=True,
                )
                sys.exit(1)

            sample = normalize_sample(
                sample_raw
            )

            contig = normalize_contig(
                contig_raw,
                sample_raw,
                sample,
            )

            (
                sequence_class,
                syntenic_group,
            ) = classify_contig(
                contig
            )

            is_pacbio = sample in PACBIO_SAMPLES

            records.append(
                SequenceRecord(
                    community=community,
                    sequence_header=header,
                    sample_raw=sample_raw,
                    sample=sample,
                    haplotype=haplotype,
                    contig_raw=contig_raw,
                    contig=contig,
                    length_bp=length_bp,
                    technology=(
                        "PacBio"
                        if is_pacbio
                        else "Illumina"
                    ),
                    is_pacbio=is_pacbio,
                    sequence_class=sequence_class,
                    syntenic_group=syntenic_group,
                )
            )

    return records


# =========================
# TABLE 1: INVENTORY
# =========================

def write_inventory(
    records: list[SequenceRecord],
    output_path: Path,
) -> None:
    """Write one row per sequence."""
    fieldnames = [
        "community",
        "sequence_header",
        "sample_raw",
        "sample",
        "haplotype",
        "contig_raw",
        "contig",
        "length_bp",
        "technology",
        "is_pacbio",
        "sequence_class",
        "syntenic_group",
    ]

    with output_path.open(
        "w",
        newline="",
        encoding="utf-8",
    ) as handle:
        writer = csv.DictWriter(
            handle,
            fieldnames=fieldnames,
            delimiter="\t",
        )

        writer.writeheader()

        for record in sorted(
            records,
            key=lambda value: (
                natural_key(value.community),
                natural_key(value.sample),
                natural_key(value.contig),
            ),
        ):
            writer.writerow(
                {
                    field: getattr(
                        record,
                        field,
                    )
                    for field in fieldnames
                }
            )


# =========================
# TABLE 2: COMMUNITY SUMMARY
# =========================

def write_community_summary(
    records: list[SequenceRecord],
    output_path: Path,
    candidate_output_path: Path,
) -> None:
    """Write the wide one-row-per-community summary."""
    all_samples = sorted(
        {
            record.sample
            for record in records
        },
        key=natural_key,
    )

    records_by_community: dict[
        str,
        list[SequenceRecord],
    ] = defaultdict(list)

    for record in records:
        records_by_community[
            record.community
        ].append(record)

    fixed_fields = [
        "community",
        "n_sequences",
        "total_length_bp",
        "n_genomes",
        "genomes_present",
        "pacbio_genomes_present",
        "n_pacbio_genomes_present",
        "has_all_5_pacbio",
    ]

    genome_count_fields = [
        f"n_{sample}"
        for sample in all_samples
    ]

    trailing_fields = [
        "pacbio_grouped_count",
        "pacbio_ungrouped_count",
        "pacbio_other_count",
        "pacbio_grouped_sequences",
        "pacbio_ungrouped_sequences",
        "pacbio_syntenic_groups",
        "pacbio_ungrouped_labels",
        "all_grouped_count",
        "all_ungrouped_count",
        "all_other_count",
    ]

    fieldnames = (
        fixed_fields
        + genome_count_fields
        + trailing_fields
    )

    summary_rows: list[dict[str, object]] = []

    for community in sorted(
        records_by_community,
        key=natural_key,
    ):
        community_records = records_by_community[
            community
        ]

        sample_counts = Counter(
            record.sample
            for record in community_records
        )

        samples_present = sorted(
            sample_counts,
            key=natural_key,
        )

        pacbio_present = [
            sample
            for sample in PACBIO_SAMPLES
            if sample_counts.get(
                sample,
                0,
            ) > 0
        ]

        pacbio_records = [
            record
            for record in community_records
            if record.is_pacbio
        ]

        pacbio_grouped = [
            record
            for record in pacbio_records
            if record.sequence_class == "grouped"
        ]

        pacbio_ungrouped = [
            record
            for record in pacbio_records
            if record.sequence_class == "ungrouped"
        ]

        pacbio_other = [
            record
            for record in pacbio_records
            if record.sequence_class == "other"
        ]

        all_grouped_count = sum(
            record.sequence_class == "grouped"
            for record in community_records
        )

        all_ungrouped_count = sum(
            record.sequence_class == "ungrouped"
            for record in community_records
        )

        all_other_count = sum(
            record.sequence_class == "other"
            for record in community_records
        )

        row: dict[str, object] = {
            "community": community,
            "n_sequences": len(
                community_records
            ),
            "total_length_bp": sum(
                record.length_bp
                for record in community_records
            ),
            "n_genomes": len(
                samples_present
            ),
            "genomes_present": ";".join(
                samples_present
            ),
            "pacbio_genomes_present": ";".join(
                pacbio_present
            ),
            "n_pacbio_genomes_present": len(
                pacbio_present
            ),
            "has_all_5_pacbio": (
                "YES"
                if set(PACBIO_SAMPLES).issubset(
                    sample_counts
                )
                else "NO"
            ),
        }

        for sample in all_samples:
            row[
                f"n_{sample}"
            ] = sample_counts.get(
                sample,
                0,
            )

        row.update(
            {
                "pacbio_grouped_count": len(
                    pacbio_grouped
                ),
                "pacbio_ungrouped_count": len(
                    pacbio_ungrouped
                ),
                "pacbio_other_count": len(
                    pacbio_other
                ),
                "pacbio_grouped_sequences": ";".join(
                    sorted(
                        {
                            f"{record.sample}:{record.contig}"
                            for record in pacbio_grouped
                        },
                        key=natural_key,
                    )
                ),
                "pacbio_ungrouped_sequences": ";".join(
                    sorted(
                        {
                            f"{record.sample}:{record.contig}"
                            for record in pacbio_ungrouped
                        },
                        key=natural_key,
                    )
                ),
                "pacbio_syntenic_groups": ";".join(
                    sorted(
                        {
                            record.syntenic_group
                            for record in pacbio_grouped
                            if record.syntenic_group
                        },
                        key=natural_key,
                    )
                ),
                "pacbio_ungrouped_labels": ";".join(
                    sorted(
                        {
                            record.syntenic_group
                            for record in pacbio_ungrouped
                            if record.syntenic_group
                        },
                        key=natural_key,
                    )
                ),
                "all_grouped_count": all_grouped_count,
                "all_ungrouped_count": all_ungrouped_count,
                "all_other_count": all_other_count,
            }
        )

        summary_rows.append(
            row
        )

    for target_path, rows in [
        (
            output_path,
            summary_rows,
        ),
        (
            candidate_output_path,
            [
                row
                for row in summary_rows
                if row["has_all_5_pacbio"] == "YES"
            ],
        ),
    ]:
        with target_path.open(
            "w",
            newline="",
            encoding="utf-8",
        ) as handle:
            writer = csv.DictWriter(
                handle,
                fieldnames=fieldnames,
                delimiter="\t",
            )

            writer.writeheader()
            writer.writerows(
                rows
            )


# =========================
# TABLE 3: PACBIO MAPPING
# =========================

def write_pacbio_chromosome_map(
    records: list[SequenceRecord],
    output_path: Path,
) -> None:
    """
    Write a canonical PacBio chromosome/ungrouped-to-community mapping.

    Grouped sequences are summarized by Group1..Group11.
    Ungrouped sequences retain their individual labels.
    """
    pacbio_records = [
        record
        for record in records
        if record.is_pacbio
        and record.sequence_class in {
            "grouped",
            "ungrouped",
        }
    ]

    grouped: dict[
        tuple[str, str],
        list[SequenceRecord],
    ] = defaultdict(list)

    for record in pacbio_records:
        canonical_label = (
            record.syntenic_group
            if record.syntenic_group
            else record.contig
        )

        grouped[
            (
                record.sequence_class,
                canonical_label,
            )
        ].append(record)

    fieldnames = [
        "sequence_class",
        "canonical_label",
        "n_sequences",
        "n_samples",
        "samples_present",
        "n_communities",
        "communities",
        "sample_sequence_details",
    ]

    with output_path.open(
        "w",
        newline="",
        encoding="utf-8",
    ) as handle:
        writer = csv.DictWriter(
            handle,
            fieldnames=fieldnames,
            delimiter="\t",
        )

        writer.writeheader()

        for (
            sequence_class,
            canonical_label,
        ) in sorted(
            grouped,
            key=lambda item: (
                item[0],
                natural_key(
                    item[1]
                ),
            ),
        ):
            label_records = grouped[
                (
                    sequence_class,
                    canonical_label,
                )
            ]

            samples = sorted(
                {
                    record.sample
                    for record in label_records
                },
                key=natural_key,
            )

            communities = sorted(
                {
                    record.community
                    for record in label_records
                },
                key=natural_key,
            )

            details = sorted(
                {
                    (
                        f"{record.sample}:"
                        f"{record.contig}@"
                        f"{record.community}"
                    )
                    for record in label_records
                },
                key=natural_key,
            )

            writer.writerow(
                {
                    "sequence_class": sequence_class,
                    "canonical_label": canonical_label,
                    "n_sequences": len(
                        label_records
                    ),
                    "n_samples": len(
                        samples
                    ),
                    "samples_present": ";".join(
                        samples
                    ),
                    "n_communities": len(
                        communities
                    ),
                    "communities": ";".join(
                        communities
                    ),
                    "sample_sequence_details": ";".join(
                        details
                    ),
                }
            )


# =========================
# FINAL VALIDATION REPORT
# =========================

def write_validation_report(
    records: list[SequenceRecord],
    output_path: Path,
) -> None:
    """Write key checks to support interpretation of the resulting tables."""
    total_records = len(
        records
    )

    communities = sorted(
        {
            record.community
            for record in records
        },
        key=natural_key,
    )

    all_samples = sorted(
        {
            record.sample
            for record in records
        },
        key=natural_key,
    )

    pacbio_records = [
        record
        for record in records
        if record.is_pacbio
    ]

    pacbio_by_sample = Counter(
        record.sample
        for record in pacbio_records
    )

    grouped_by_sample = Counter(
        record.sample
        for record in pacbio_records
        if record.sequence_class == "grouped"
    )

    ungrouped_by_sample = Counter(
        record.sample
        for record in pacbio_records
        if record.sequence_class == "ungrouped"
    )

    with output_path.open(
        "w",
        encoding="utf-8",
    ) as handle:
        handle.write(
            "metric\tvalue\n"
        )

        handle.write(
            f"partition_fasta_files\t{len(communities)}\n"
        )

        handle.write(
            f"total_sequences\t{total_records}\n"
        )

        handle.write(
            f"total_genomes\t{len(all_samples)}\n"
        )

        handle.write(
            f"pacbio_sequences\t{len(pacbio_records)}\n"
        )

        for sample in PACBIO_SAMPLES:
            handle.write(
                f"{sample}_total_sequences\t"
                f"{pacbio_by_sample.get(sample, 0)}\n"
            )

            handle.write(
                f"{sample}_grouped_sequences\t"
                f"{grouped_by_sample.get(sample, 0)}\n"
            )

            handle.write(
                f"{sample}_ungrouped_sequences\t"
                f"{ungrouped_by_sample.get(sample, 0)}\n"
            )


# =========================
# MAIN
# =========================

def main() -> None:
    """Run the complete community inventory workflow."""
    start_time = datetime.now()

    print("=" * 70, flush=True)
    print("PGGB 24-GENOME COMMUNITY SEQUENCE INVENTORY", flush=True)
    print(
        f"Start           : {start_time:%Y-%m-%d %H:%M:%S}",
        flush=True,
    )
    print(
        f"PARTITION_DIR   : {PARTITION_DIR}",
        flush=True,
    )
    print(
        f"OUTPUT_DIR      : {OUTPUT_DIR}",
        flush=True,
    )
    print(
        f"COMMUNITY_GLOB  : {COMMUNITY_GLOB}",
        flush=True,
    )
    print(
        f"PACBIO_SAMPLES  : {','.join(PACBIO_SAMPLES)}",
        flush=True,
    )
    print("=" * 70, flush=True)

    if not PARTITION_DIR.is_dir():
        print(
            f"[ERROR] PARTITION_DIR does not exist: {PARTITION_DIR}",
            flush=True,
        )
        sys.exit(1)

    OUTPUT_DIR.mkdir(
        parents=True,
        exist_ok=True,
    )

    fasta_paths = sorted(
        PARTITION_DIR.glob(
            COMMUNITY_GLOB
        ),
        key=lambda path: natural_key(
            path.name
        ),
    )

    if not fasta_paths:
        print(
            f"[ERROR] No community FASTA files matched "
            f"'{COMMUNITY_GLOB}' in {PARTITION_DIR}",
            flush=True,
        )
        sys.exit(1)

    print(
        f"\nCommunity FASTA files found: {len(fasta_paths)}\n",
        flush=True,
    )

    records = build_inventory(
        fasta_paths
    )

    if not records:
        print(
            "[ERROR] No sequences were found in the community FASTA files.",
            flush=True,
        )
        sys.exit(1)

    inventory_path = (
        OUTPUT_DIR
        / "community_sequence_inventory.tsv"
    )

    summary_path = (
        OUTPUT_DIR
        / "community_summary.tsv"
    )

    candidate_path = (
        OUTPUT_DIR
        / "candidate_communities_all_5_pacbio.tsv"
    )

    chromosome_map_path = (
        OUTPUT_DIR
        / "pacbio_chromosome_to_communities.tsv"
    )

    validation_path = (
        OUTPUT_DIR
        / "inventory_validation_summary.tsv"
    )

    write_inventory(
        records,
        inventory_path,
    )

    write_community_summary(
        records,
        summary_path,
        candidate_path,
    )

    write_pacbio_chromosome_map(
        records,
        chromosome_map_path,
    )

    write_validation_report(
        records,
        validation_path,
    )

    end_time = datetime.now()

    print("\n" + "=" * 70, flush=True)
    print("COMMUNITY INVENTORY COMPLETED", flush=True)
    print(
        f"Sequences processed : {len(records)}",
        flush=True,
    )
    print(
        f"Communities         : {len(fasta_paths)}",
        flush=True,
    )
    print(
        f"Inventory           : {inventory_path}",
        flush=True,
    )
    print(
        f"Community summary   : {summary_path}",
        flush=True,
    )
    print(
        f"PacBio candidates   : {candidate_path}",
        flush=True,
    )
    print(
        f"Chromosome map      : {chromosome_map_path}",
        flush=True,
    )
    print(
        f"Validation summary  : {validation_path}",
        flush=True,
    )
    print(
        f"Total runtime       : {end_time - start_time}",
        flush=True,
    )
    print(
        f"End                 : {end_time:%Y-%m-%d %H:%M:%S}",
        flush=True,
    )
    print("=" * 70, flush=True)


if __name__ == "__main__":
    main()
