#!/usr/bin/env python3
"""
run_balanced_pca_seed.py

Runs one replicate of the partition-balanced PCA robustness analysis.

For a single random seed, the script:

  1. Samples an exact number of SNPs approximately equally across partitions.
  2. Builds one balanced SNP matrix for PGGB.
  3. Builds one balanced SNP matrix for minigraph-cactus.
  4. Runs PCA independently for each method.
  5. Saves PCA coordinates, variance explained, and partition sampling tables.

The script uses the complete imputed SNP matrices and feature metadata already
generated by the main population-structure pipeline.

Usage:

    python run_balanced_pca_seed.py \
        --seed 42 \
        --total-snps 1000 \
        --metadata sample_metadata.tsv \
        --pggb-matrix PGGB_snp_matrix_imputed.tsv \
        --pggb-features PGGB_snp_feature_metadata.tsv \
        --cactus-matrix Cactus_snp_matrix_imputed.tsv \
        --cactus-features Cactus_snp_feature_metadata.tsv \
        --output-dir robustness/seed_42
"""

import argparse
import re
import sys
from datetime import datetime
from pathlib import Path

import numpy as np
import pandas as pd


def parse_arguments():
    """Parse command-line arguments."""
    parser = argparse.ArgumentParser(
        description="Run one balanced-PCA robustness replicate."
    )

    parser.add_argument("--seed", required=True, type=int)
    parser.add_argument("--total-snps", required=True, type=int)
    parser.add_argument("--metadata", required=True)
    parser.add_argument("--pggb-matrix", required=True)
    parser.add_argument("--pggb-features", required=True)
    parser.add_argument("--cactus-matrix", required=True)
    parser.add_argument("--cactus-features", required=True)
    parser.add_argument("--output-dir", required=True)

    return parser.parse_args()


def natural_partition_key(label):
    """Return a numeric sorting key for community.N and groupN labels."""
    match = re.search(r"(\d+)$", label)
    return int(match.group(1)) if match else label


def extract_partition(vcf_file, source):
    """Extract a standardized partition label from a VCF path."""
    path = str(vcf_file)

    if source == "PGGB":
        match = re.search(r"community\.(\d+)", path)
        if match:
            return f"community.{int(match.group(1))}"

    elif source == "Cactus":
        match = re.search(r"(?:^|/)group(\d+)(?:/|$)", path)

        if not match:
            match = re.search(r"cactus_group(\d+)_", path)

        if match:
            return f"group{int(match.group(1))}"

    raise ValueError(
        f"Could not extract a {source} partition from VCF path: {path}"
    )


def allocate_exact_total(partition_sizes, total_snps, seed):
    """
    Allocate an exact total number of SNPs as evenly as possible.

    When the total is not divisible by the number of partitions, remainder
    SNPs are assigned reproducibly among tied partitions using the seed.
    """
    partitions = sorted(partition_sizes, key=natural_partition_key)
    available_total = sum(partition_sizes.values())

    if total_snps > available_total:
        raise ValueError(
            f"Requested {total_snps} SNPs, but only {available_total} "
            "features are available."
        )

    allocation = {partition: 0 for partition in partitions}
    remaining = total_snps
    rng = np.random.default_rng(seed)

    while remaining > 0:
        eligible = [
            partition
            for partition in partitions
            if allocation[partition] < partition_sizes[partition]
        ]

        if not eligible:
            raise RuntimeError("Could not complete the SNP allocation.")

        minimum = min(allocation[partition] for partition in eligible)

        tied = [
            partition
            for partition in eligible
            if allocation[partition] == minimum
        ]

        chosen = str(rng.choice(tied))
        allocation[chosen] += 1
        remaining -= 1

    return allocation


def load_and_validate(matrix_path, feature_path, metadata):
    """Load one matrix and its matching feature metadata."""
    matrix = pd.read_csv(
        matrix_path,
        sep="\t",
        index_col=0,
    )

    features = pd.read_csv(
        feature_path,
        sep="\t",
        index_col=0,
    )

    if matrix.empty:
        raise ValueError(f"SNP matrix is empty: {matrix_path}")

    if "vcf_file" not in features.columns:
        raise ValueError(
            f"Feature metadata lacks the vcf_file column: {feature_path}"
        )

    missing_features = matrix.index.difference(features.index)

    if len(missing_features) > 0:
        raise ValueError(
            f"{len(missing_features)} matrix features are absent from "
            f"the metadata: {feature_path}"
        )

    expected_samples = metadata["sample_id"].tolist()

    if matrix.columns.tolist() != expected_samples:
        missing_samples = [
            sample for sample in expected_samples if sample not in matrix.columns
        ]

        if missing_samples:
            raise ValueError(
                f"Matrix is missing metadata samples: {missing_samples}"
            )

        matrix = matrix.loc[:, expected_samples]

    return matrix, features.loc[matrix.index].copy()


def sample_balanced_matrix(
    matrix,
    features,
    source,
    total_snps,
    seed,
):
    """Sample a balanced SNP matrix and return its sampling summary."""
    features = features.copy()

    features["partition"] = features["vcf_file"].map(
        lambda value: extract_partition(value, source)
    )

    partition_sizes = (
        features["partition"]
        .value_counts()
        .to_dict()
    )

    allocation = allocate_exact_total(
        partition_sizes,
        total_snps,
        seed,
    )

    rng = np.random.default_rng(seed)
    selected_features = []

    for partition in sorted(allocation, key=natural_partition_key):
        candidates = features.index[
            features["partition"] == partition
        ].to_numpy()

        selected = rng.choice(
            candidates,
            size=allocation[partition],
            replace=False,
        )

        selected_features.extend(selected.tolist())

    selected_features = rng.permutation(
        selected_features
    ).tolist()

    balanced = matrix.loc[selected_features].copy()

    sampling_rows = []

    for partition in sorted(partition_sizes, key=natural_partition_key):
        available = int(partition_sizes[partition])
        selected = int(allocation[partition])

        sampling_rows.append(
            {
                "partition": partition,
                "available_snps": available,
                "selected_snps": selected,
                "selected_pct": round(selected / available * 100, 4),
            }
        )

    return (
        balanced,
        features.loc[selected_features].copy(),
        pd.DataFrame(sampling_rows),
    )


def run_pca(feature_by_sample_matrix):
    """
    Run PCA using samples as observations and SNPs as features.

    PCA is calculated through singular-value decomposition after centering
    each SNP feature. Features are not variance-scaled, matching the main PCA.
    """
    sample_by_feature = feature_by_sample_matrix.T.to_numpy(dtype=float)

    centered = sample_by_feature - sample_by_feature.mean(
        axis=0,
        keepdims=True,
    )

    u_matrix, singular_values, _ = np.linalg.svd(
        centered,
        full_matrices=False,
    )

    scores = u_matrix * singular_values

    denominator = max(sample_by_feature.shape[0] - 1, 1)
    eigenvalues = (singular_values ** 2) / denominator

    if eigenvalues.sum() == 0:
        raise ValueError("PCA produced zero total variance.")

    variance_explained = eigenvalues / eigenvalues.sum() * 100

    return scores, variance_explained


def save_method_results(
    source,
    matrix,
    selected_metadata,
    sampling_summary,
    sample_metadata,
    output_dir,
    seed,
):
    """Run PCA and save all outputs for one graph method."""
    method_dir = output_dir / source
    method_dir.mkdir(parents=True, exist_ok=True)

    scores, variance_explained = run_pca(matrix)

    number_of_axes = min(
        3,
        scores.shape[1],
    )

    score_columns = [
        f"PC{index}"
        for index in range(1, number_of_axes + 1)
    ]

    coordinates = pd.DataFrame(
        scores[:, :number_of_axes],
        columns=score_columns,
    )

    coordinates.insert(
        0,
        "sample_id",
        matrix.columns.tolist(),
    )

    coordinates = coordinates.merge(
        sample_metadata,
        on="sample_id",
        how="left",
        validate="one_to_one",
    )

    coordinates.insert(
        1,
        "seed",
        seed,
    )

    coordinates.insert(
        2,
        "method",
        source,
    )

    variance = pd.DataFrame(
        {
            "PC": [
                f"PC{index}"
                for index in range(1, len(variance_explained) + 1)
            ],
            "pct_variance": variance_explained,
            "cumulative_variance": np.cumsum(variance_explained),
        }
    )

    coordinates.to_csv(
        method_dir / "pca_coordinates.tsv",
        sep="\t",
        index=False,
    )

    variance.to_csv(
        method_dir / "pca_variance_explained.tsv",
        sep="\t",
        index=False,
    )

    sampling_summary.to_csv(
        method_dir / "partition_sampling.tsv",
        sep="\t",
        index=False,
    )

    selected_metadata.to_csv(
        method_dir / "selected_feature_metadata.tsv",
        sep="\t",
    )

    with open(
        method_dir / "selected_features.txt",
        "w",
        encoding="utf-8",
    ) as handle:
        for feature_id in matrix.index:
            handle.write(f"{feature_id}\n")


def main():
    """Run one robustness replicate for PGGB and Cactus."""
    arguments = parse_arguments()
    start_time = datetime.now()

    if arguments.total_snps < 1:
        print("[ERROR] --total-snps must be positive.", flush=True)
        sys.exit(1)

    metadata_path = Path(arguments.metadata)

    if not metadata_path.is_file():
        print(
            f"[ERROR] Metadata file not found: {metadata_path}",
            flush=True,
        )
        sys.exit(1)

    metadata = pd.read_csv(
        metadata_path,
        sep="\t",
        dtype=str,
    )

    required_metadata_columns = {"sample_id", "region"}

    missing_columns = required_metadata_columns.difference(
        metadata.columns
    )

    if missing_columns:
        print(
            f"[ERROR] Metadata lacks columns: {sorted(missing_columns)}",
            flush=True,
        )
        sys.exit(1)

    output_dir = Path(arguments.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    print("=" * 65, flush=True)
    print("BALANCED PCA ROBUSTNESS REPLICATE", flush=True)
    print(f"Start       : {start_time:%Y-%m-%d %H:%M:%S}", flush=True)
    print(f"Seed        : {arguments.seed}", flush=True)
    print(f"Total SNPs  : {arguments.total_snps}", flush=True)
    print(f"Output      : {output_dir}", flush=True)
    print("=" * 65, flush=True)

    input_sets = {
        "PGGB": (
            Path(arguments.pggb_matrix),
            Path(arguments.pggb_features),
        ),
        "Cactus": (
            Path(arguments.cactus_matrix),
            Path(arguments.cactus_features),
        ),
    }

    for source, (matrix_path, feature_path) in input_sets.items():
        print(f"\n[{source}]", flush=True)

        try:
            matrix, features = load_and_validate(
                matrix_path,
                feature_path,
                metadata,
            )

            (
                balanced_matrix,
                selected_metadata,
                sampling_summary,
            ) = sample_balanced_matrix(
                matrix,
                features,
                source,
                arguments.total_snps,
                arguments.seed,
            )

            save_method_results(
                source=source,
                matrix=balanced_matrix,
                selected_metadata=selected_metadata,
                sampling_summary=sampling_summary,
                sample_metadata=metadata,
                output_dir=output_dir,
                seed=arguments.seed,
            )

        except (ValueError, RuntimeError) as error:
            print(f"[ERROR] {source}: {error}", flush=True)
            sys.exit(1)

        print(
            f"  Selected SNPs : {balanced_matrix.shape[0]}",
            flush=True,
        )
        print(
            f"  Samples       : {balanced_matrix.shape[1]}",
            flush=True,
        )

    end_time = datetime.now()

    print("\n" + "=" * 65, flush=True)
    print("ROBUSTNESS REPLICATE COMPLETED", flush=True)
    print(f"Seed          : {arguments.seed}", flush=True)
    print(f"Total runtime : {end_time - start_time}", flush=True)
    print(f"End           : {end_time:%Y-%m-%d %H:%M:%S}", flush=True)
    print("=" * 65, flush=True)


if __name__ == "__main__":
    main()
