#!/bin/bash

# =============================================================
# run_balanced_pca_pipeline.sh
#
# Runs a partition-balanced PCA analysis for PGGB and Cactus.
# Reuses the complete matrices generated by the original pipeline.
# =============================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

POPULATION_BASE="/Storage/data1/isabella.gallego/MAESTRIA/population_structure"
METADATA_FILE="${SCRIPT_DIR}/sample_metadata.tsv"
ANALYSIS_SCRIPT="${SCRIPT_DIR}/analyze_population_structure.R"
COMPARISON_SCRIPT="${SCRIPT_DIR}/compare_pggb_cactus_pca.R"
SAMPLING_SCRIPT="${SCRIPT_DIR}/sample_balanced_snps.py"

PYTHON="${PYTHON:-python}"
RSCRIPT="${RSCRIPT:-Rscript}"
TOTAL_SNPS="${TOTAL_SNPS:-1000}"
RANDOM_SEED="${RANDOM_SEED:-42}"

PGGB_MATRIX="${POPULATION_BASE}/PGGB/PGGB_snp_matrix_imputed.tsv"
PGGB_FEATURES="${POPULATION_BASE}/PGGB/PGGB_snp_feature_metadata.tsv"
CACTUS_MATRIX="${POPULATION_BASE}/Cactus/Cactus_snp_matrix_imputed.tsv"
CACTUS_FEATURES="${POPULATION_BASE}/Cactus/Cactus_snp_feature_metadata.tsv"

BALANCED_BASE="${POPULATION_BASE}/balanced"
PGGB_OUTPUT="${BALANCED_BASE}/PGGB"
CACTUS_OUTPUT="${BALANCED_BASE}/Cactus"
COMPARISON_OUTPUT="${BALANCED_BASE}/comparison"

mkdir -p "${PGGB_OUTPUT}" "${CACTUS_OUTPUT}" "${COMPARISON_OUTPUT}"

for required_file in \
    "${METADATA_FILE}" \
    "${ANALYSIS_SCRIPT}" \
    "${COMPARISON_SCRIPT}" \
    "${SAMPLING_SCRIPT}" \
    "${PGGB_MATRIX}" \
    "${PGGB_FEATURES}" \
    "${CACTUS_MATRIX}" \
    "${CACTUS_FEATURES}"
do
    if [[ ! -f "${required_file}" ]]; then
        echo "[ERROR] Required file not found: ${required_file}"
        exit 1
    fi
done

echo "============================================================="
echo "PARTITION-BALANCED PCA PIPELINE"
echo "Start       : $(date '+%Y-%m-%d %H:%M:%S')"
echo "TOTAL_SNPS  : ${TOTAL_SNPS}"
echo "RANDOM_SEED : ${RANDOM_SEED}"
echo "Output      : ${BALANCED_BASE}"
echo "============================================================="
echo ""

echo "[1/4] Sampling the balanced PGGB SNP set..."

"${PYTHON}" "${SAMPLING_SCRIPT}" \
    --source "PGGB" \
    --matrix "${PGGB_MATRIX}" \
    --features "${PGGB_FEATURES}" \
    --total-snps "${TOTAL_SNPS}" \
    --seed "${RANDOM_SEED}" \
    --output-prefix "${PGGB_OUTPUT}/PGGB_balanced"

echo ""
echo "[2/4] Sampling the balanced Cactus SNP set..."

"${PYTHON}" "${SAMPLING_SCRIPT}" \
    --source "Cactus" \
    --matrix "${CACTUS_MATRIX}" \
    --features "${CACTUS_FEATURES}" \
    --total-snps "${TOTAL_SNPS}" \
    --seed "${RANDOM_SEED}" \
    --output-prefix "${CACTUS_OUTPUT}/Cactus_balanced"

echo ""
echo "[3/4] Running balanced PCA and distance analyses..."

"${RSCRIPT}" "${ANALYSIS_SCRIPT}" \
    "${PGGB_OUTPUT}/PGGB_balanced_snp_matrix_imputed.tsv" \
    "${METADATA_FILE}" \
    "PGGB_balanced" \
    "${PGGB_OUTPUT}"

"${RSCRIPT}" "${ANALYSIS_SCRIPT}" \
    "${CACTUS_OUTPUT}/Cactus_balanced_snp_matrix_imputed.tsv" \
    "${METADATA_FILE}" \
    "Cactus_balanced" \
    "${CACTUS_OUTPUT}"

echo ""
echo "[4/4] Generating the balanced PCA comparison panel..."

"${RSCRIPT}" "${COMPARISON_SCRIPT}" \
    "${PGGB_OUTPUT}/PGGB_balanced_pca_coordinates.tsv" \
    "${CACTUS_OUTPUT}/Cactus_balanced_pca_coordinates.tsv" \
    "${COMPARISON_OUTPUT}/PGGB_vs_Cactus_balanced_PCA.pdf"

echo ""
echo "============================================================="
echo "BALANCED PCA PIPELINE COMPLETED"
echo "Total SNPs per method : ${TOTAL_SNPS}"
echo "Random seed           : ${RANDOM_SEED}"
echo "PGGB results          : ${PGGB_OUTPUT}"
echo "Cactus results        : ${CACTUS_OUTPUT}"
echo "Comparison            : ${COMPARISON_OUTPUT}"
echo "============================================================="
